# Setup
title:        个人全栈开发经验分享
name:         个人全栈开发经验分享
tagline:      总结知识，分享感悟，欢迎关注个人全栈开发经验分享
baseurl:      ""
#paginate:     1
locale:       "zh"
siteurl: https://www.cdroom.net
# timezone: '+0800'
permalink: /:year/:month/:day/:title.html
# About/contact
author:
  name:       全栈布布
  url:        https://www.cdroom.net

# Gems
#gems:
#  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman