# Setup
title:        云梦斋
name:         云梦斋
tagline:      总结知识，分享感悟，欢迎关注云梦斋
baseurl:      ""
#paginate:     1
locale:       "zh"
siteurl: https://www.cdroom.net
# timezone: '+0800'
permalink: /:year/:month/:day/:title.html
# About/contact
author:
  name:       云梦斋主人
  url:        https://www.cdroom.net

# Gems
#gems:
#  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman